use_frameworks!

platform :ios, '10.0'

target 'TFSBarcodeScanner_Example' do
  pod 'TFSBarcodeScanner', :path => '../'

  target 'TFSBarcodeScanner_Tests' do
    inherit! :search_paths

    
  end
end
